import { IsNotEmpty, IsString, Length } from 'class-validator'

/**
 * Data Transfer Object for the accept invitation endpoint.
 *
 * Validated via NestJS `ValidationPipe` before reaching the service layer.
 *
 * @layer DTO
 */
export class AcceptInvitationDto {
  /**
   * Opaque invitation token from the invitation email link.
   *
   * @remarks
   * Invitation tokens are generated by `generateSecureToken(32)` which produces
   * exactly 64 hex characters (32 bytes × 2 hex chars per byte). The fixed-length
   * constraint prevents DoS via oversized hash inputs on the unauthenticated
   * `/accept` endpoint.
   */
  @IsString()
  @IsNotEmpty()
  @Length(64, 64)
  token!: string

  /**
   * Display name for the new account.
   * Minimum 2 characters to prevent single-character placeholders.
   */
  @IsString()
  @IsNotEmpty()
  @Length(2, 100)
  name!: string

  /**
   * Plaintext password for the new account.
   *
   * @remarks
   * The 8-character floor here is STRUCTURAL, not the deployment's policy: it is the lowest
   * NIST SP 800-63B-4 §3.1.1.1 permits under any circumstance, and it is what a decorator
   * can express — decorators are evaluated when the class is defined, before any
   * configuration exists. The policy floor is `password.minLength` (default 15, as the
   * standard requires of a single-factor password), enforced by `PasswordService` and
   * answering this same `auth.validation` code and details shape.
   *
   * Maximum 128 characters as a practical
   * input bound to prevent DoS via pathological scrypt inputs.
   * The service layer hashes this value immediately — it is never logged or persisted in plaintext
   * BY THIS LIBRARY. A breach checker you supply receives it by contract, and an error it raises
   * is a place it can be; see `PasswordService.assertNotCompromised` for the ceiling.
   */
  @IsString()
  @Length(8, 128)
  password!: string
}
