import { IsNotEmpty, IsString, Length } from 'class-validator'

/**
 * Data Transfer Object for the accept invitation endpoint.
 *
 * Validated via NestJS `ValidationPipe` before reaching the service layer.
 */
export class AcceptInvitationDto {
  /**
   * Opaque invitation token from the invitation email link.
   *
   * @remarks
   * Invitation tokens are generated by `generateSecureToken(32)` which produces
   * exactly 64 hex characters (32 bytes × 2 hex chars per byte). The fixed-length
   * constraint prevents DoS via oversized hash inputs on the unauthenticated
   * `/accept` endpoint.
   */
  @IsString()
  @IsNotEmpty()
  @Length(64, 64)
  token!: string

  /**
   * Display name for the new account.
   * Minimum 2 characters to prevent single-character placeholders.
   */
  @IsString()
  @IsNotEmpty()
  @Length(2, 100)
  name!: string

  /**
   * Plaintext password for the new account.
   *
   * @remarks
   * Minimum 8 characters for usability; maximum 128 characters as a practical
   * input bound to prevent DoS via pathological scrypt inputs.
   * The service layer hashes this value immediately — it is never logged or
   * persisted in plaintext.
   */
  @IsString()
  @Length(8, 128)
  password!: string
}
