import { IsNotEmpty, IsString, Matches, MaxLength } from 'class-validator'

/**
 * Data Transfer Object for the MFA disable endpoint.
 *
 * Submitted when a user requests to turn off multi-factor authentication on
 * their account. The endpoint requires a valid TOTP code from the user's
 * authenticator app to confirm the action.
 *
 * @remarks
 * **TOTP codes only** — recovery codes are intentionally not accepted for
 * disabling MFA. This is a deliberate product security decision: if a user
 * has lost access to their authenticator app and is using recovery codes, they
 * should not be able to silently disable MFA (which would leave the account
 * unprotected). Recovery without a TOTP device requires administrative
 * intervention via a support channel.
 */
export class MfaDisableDto {
  /**
   * The 6-digit TOTP code generated by the user's authenticator app.
   *
   * Must be exactly 6 decimal digits. Recovery codes are not accepted by design.
   * Alphabetic characters, spaces, or other symbols are rejected before reaching
   * the service layer.
   */
  @MaxLength(6)
  @Matches(/^\d{6}$/, { message: 'code must be exactly 6 digits' })
  @IsString()
  @IsNotEmpty()
  code!: string
}
