import { IsNotEmpty, IsString, Matches, MaxLength } from 'class-validator'

/**
 * Data Transfer Object for the MFA TOTP verification step during setup.
 *
 * Submitted after `POST /mfa/setup` to confirm that the user has successfully
 * enrolled their authenticator app by providing a valid code.
 */
export class MfaVerifyDto {
  /**
   * The 6-digit TOTP code generated by the user's authenticator app.
   *
   * Must be exactly 6 decimal digits — alphabetic characters, spaces, or other
   * symbols are rejected before reaching the service layer.
   */
  @MaxLength(6)
  @Matches(/^\d{6}$/, { message: 'code must be exactly 6 digits' })
  @IsString()
  @IsNotEmpty()
  code!: string
}
