import { IsNotEmpty, IsString, Matches, MaxLength } from 'class-validator'

/**
 * Data Transfer Object for the MFA recovery code regeneration endpoint.
 *
 * Submitted when an MFA-enabled user wants to rotate their recovery codes
 * (e.g. after suspecting they have been written down somewhere insecure, or
 * after consuming several entries from the original list). The endpoint
 * requires a valid TOTP code from the user's authenticator app to confirm
 * the action.
 *
 * @remarks
 * **TOTP codes only** — recovery codes are intentionally not accepted as
 * the proof factor here. If a user has lost access to their authenticator
 * and is relying on recovery codes, the safe path is to disable MFA and
 * re-enrol (which forces a fresh secret AND a fresh recovery code set),
 * not to silently rotate recovery codes using one of the codes the user
 * may already have leaked.
 *
 * @layer DTO
 */
export class MfaRegenerateRecoveryCodesDto {
  /**
   * The 6-digit TOTP code generated by the user's authenticator app.
   *
   * Must be exactly 6 decimal digits. Recovery codes are not accepted by design.
   * Alphabetic characters, spaces, or other symbols are rejected before reaching
   * the service layer.
   */
  @MaxLength(6)
  @Matches(/^\d{6}$/, { message: 'code must be exactly 6 digits' })
  @IsString()
  @IsNotEmpty()
  code!: string
}
