import { IsNotEmpty, IsString, MaxLength } from 'class-validator'

/**
 * Query parameters for the OAuth callback endpoint (`GET /oauth/:provider/callback`).
 *
 * Both `code` and `state` are received from the OAuth provider redirect and must
 * be present and within reasonable length bounds before being forwarded to the
 * service layer. Length limits prevent oversized payloads from reaching the token
 * exchange HTTP call and the SHA-256 Redis key lookup.
 */
export class OAuthCallbackQueryDto {
  /**
   * Authorization code received from the OAuth provider.
   *
   * Forwarded to `plugin.exchangeCode()` which POSTs it to the provider's token
   * endpoint. OAuth authorization codes are typically 32–512 characters; 2048
   * is a safe upper bound that rejects clearly malformed payloads.
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(2048)
  code!: string

  /**
   * CSRF state nonce returned by the OAuth provider.
   *
   * Must match the nonce generated by `initiateOAuth()` and stored in Redis
   * under `os:{sha256(state)}`. The raw nonce is 64 hex characters (32 bytes);
   * 128 is a generous upper bound for future provider variations.
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  state!: string
}
