import { IsNotEmpty, IsOptional, IsString, MaxLength, ValidateIf } from 'class-validator'

/**
 * Query parameters for the OAuth callback endpoint (`GET /oauth/:provider/callback`).
 *
 * `state` is always required; `code` is required except on the error callback RFC 6749
 * §4.1.2.1 defines, which carries `error` instead. Length limits prevent oversized payloads
 * from reaching the token exchange HTTP call and the SHA-256 Redis key lookup.
 *
 * The remaining fields (`iss`, `scope`, `authuser`, `prompt`, `hd`) are
 * standard OIDC / Google Account-chooser parameters that providers append to
 * the redirect. They are accepted but never read by the service — declared
 * here so the controller-level `ValidationPipe(forbidNonWhitelisted: true)`
 * does not 400 the callback when a provider sends them. See:
 *
 *   - OAuth 2.0 Issuer Identification (RFC 9207) for `iss`
 *   - https://accounts.google.com docs for `authuser`, `prompt`, `hd`
 *   - https://datatracker.ietf.org/doc/html/rfc6749#section-3.3 for `scope`
 *
 * @layer DTO
 */
export class OAuthCallbackQueryDto {
  /**
   * Authorization code received from the OAuth provider.
   *
   * Forwarded to `plugin.exchangeCode()` which POSTs it to the provider's token
   * endpoint. OAuth authorization codes are typically 32–512 characters; 2048
   * is a safe upper bound that rejects clearly malformed payloads.
   *
   * Absent on the error callback RFC 6749 §4.1.2.1 defines — the response a provider sends
   * when the user declines consent. Required whenever `error` is absent, so a callback
   * carrying neither is still the malformed request it always was.
   */
  // `null` as well as `undefined`, so this conditional excludes exactly what `@IsOptional()`
  // excludes everywhere else in this library — its predicate is
  // `value !== null && value !== undefined`. A query string cannot carry `null`, so no callback
  // reaches this with one and the wire behaviour is unchanged; the alignment matters because the
  // declared overlay models presence with one rule for every DTO, and a predicate that read
  // `null` as *present* would make this the single field the overlay describes wrongly.
  @ValidateIf((query: OAuthCallbackQueryDto) => query.error === undefined || query.error === null)
  @IsString()
  @IsNotEmpty()
  @MaxLength(2048)
  code?: string

  /**
   * The provider's error code (RFC 6749 §4.1.2.1) — `access_denied` when the user clicks
   * "Cancel" at the consent screen, plus `server_error`, `temporarily_unavailable` and the
   * rest.
   *
   * Declared so that response reaches the library's OAuth error handling instead of the
   * `ValidationPipe`, which used to 400 it for the missing `code`: a user who simply changed
   * their mind saw a raw validation envelope rather than the configured error redirect. The
   * value is logged and never echoed to the caller — the response stays `auth.oauth_failed`,
   * so the provider cannot choose what appears in a redirect URL the browser follows.
   */
  @IsOptional()
  @IsString()
  @MaxLength(128)
  error?: string

  /**
   * Human-readable detail accompanying `error` (RFC 6749 §4.1.2.1). Accepted so the
   * `ValidationPipe` does not reject the callback; logged with `error`, never echoed.
   */
  @IsOptional()
  @IsString()
  @MaxLength(512)
  error_description?: string

  /**
   * URI of a provider page describing `error` (RFC 6749 §4.1.2.1). Accepted so the
   * `ValidationPipe` does not reject the callback; never followed and never echoed.
   */
  @IsOptional()
  @IsString()
  @MaxLength(512)
  error_uri?: string

  /**
   * CSRF state nonce returned by the OAuth provider.
   *
   * Must match the nonce generated by `initiateOAuth()` and stored in Redis
   * under `os:{sha256(state)}`. The raw nonce is 64 hex characters (32 bytes);
   * 128 is a generous upper bound for future provider variations.
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  state!: string

  /**
   * OIDC issuer identifier (RFC 9207). Echoed back by providers that advertise
   * their issuer in the discovery document — Google currently sends
   * `https://accounts.google.com`. Accepted but unused; the service derives
   * the provider from the URL path, not from this field.
   */
  @IsOptional()
  @IsString()
  @MaxLength(512)
  iss?: string

  /**
   * Space-delimited list of scopes actually granted by the user, per RFC 6749
   * §3.3. The lib does not enforce minimum scopes here — the profile fetch
   * surfaces missing data via the `IUserRepository` mapping instead.
   */
  @IsOptional()
  @IsString()
  @MaxLength(2048)
  scope?: string

  /**
   * Google Account-chooser index (`0`, `1`, …). Identifies which of the
   * signed-in Google accounts in the user's browser authorised the request.
   * Accepted as a generic string to stay agnostic of Google-specific shape.
   */
  @IsOptional()
  @IsString()
  @MaxLength(16)
  authuser?: string

  /**
   * Prompt that was shown to the user (`none`, `consent`, `select_account`,
   * or any combination thereof). Sent back by Google so SPAs can react to a
   * forced re-consent. Validation here is shape-only — semantics are the
   * provider's concern.
   */
  @IsOptional()
  @IsString()
  @MaxLength(64)
  prompt?: string

  /**
   * Hosted-domain hint sent by Google Workspace — the email's domain when the
   * authorising account belongs to a managed organisation (e.g. `example.com`).
   * Useful for consumer apps that gate features by tenant; unused by the lib.
   */
  @IsOptional()
  @IsString()
  @MaxLength(253)
  hd?: string
}
