/**
 * JWT payload type definitions for @bymax-one/nest-auth.
 *
 * Three distinct token types prevent cross-context token misuse:
 *  - DashboardJwtPayload — regular tenant users
 *  - PlatformJwtPayload  — platform administrators
 *  - MfaTempPayload      — short-lived challenge token during MFA flow
 *
 * @remarks
 * `emailVerified` is intentionally absent from all payloads; it is not a JWT
 * claim. Status fields are snapshots captured at issuance time and may diverge
 * from the database after subsequent state transitions.
 *
 * These interfaces represent the shape of a **decoded and verified** token.
 * When signing tokens, `iat` and `exp` are populated automatically by
 * `@nestjs/jwt` — do not include them in the signing payload.
 *
 * @layer Interface
 */

/**
 * JWT payload for dashboard (tenant) user access tokens.
 *
 * Issued by TokenManagerService after successful login or MFA verification.
 * The literal `type: 'dashboard'` discriminant prevents accidental acceptance
 * of platform tokens in dashboard guards and vice-versa.
 */
export interface DashboardJwtPayload {
  /** Unique JWT ID (UUID v4) generated by TokenManagerService for revocation. */
  jti: string
  /** Subject — the authenticated user's internal identifier. */
  sub: string
  /** Tenant the user belongs to; used for data isolation. */
  tenantId: string
  /** User's assigned role within the tenant (e.g. `'admin'`, `'member'`). */
  role: string
  /** Discriminant literal — always `'dashboard'`. Prevents token type confusion. */
  type: 'dashboard'
  /**
   * Snapshot of the user's account status at token issuance time.
   * May diverge from the current database value after status changes.
   * The library re-validates status against a Redis cache on each authenticated
   * request (TTL controlled by `userStatusCacheTtlSeconds` in module options).
   */
  status: string
  /**
   * Whether MFA (TOTP) is currently enabled on the user's account.
   *
   * Stamped at token issuance. When `true`, the `MfaRequiredGuard` enforces that
   * `mfaVerified` is also `true` before granting access to protected resources.
   *
   * The Redis session persists this flag, so rotation carries it across — and rotation
   * additionally re-stamps it from the account it re-reads whenever the two diverge. Both
   * matter: without the first, every rotation would silently drop a session out of MFA
   * enforcement; without the second, a session created while MFA was off would stay exempt
   * for the refresh token's whole lifetime whenever the host enables MFA through its own
   * admin surface rather than this library's `verifyAndEnable`.
   */
  mfaEnabled: boolean
  /** Whether the user completed MFA verification before this token was issued. */
  mfaVerified: boolean
  /**
   * The user's token **epoch** at issuance — a per-user generation counter the server bumps to
   * invalidate every outstanding access token at once (a password reset). The guards reject a
   * token whose epoch is below the user's stored epoch.
   *
   * Optional: a token issued before the field existed carries none, which reads as `0` and is
   * never rejected while the stored epoch is also `0` — the mechanism stays inert until the
   * first bump.
   */
  epoch?: number
  /** Issued-at timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  iat: number
  /** Expiration timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  exp: number
}

/**
 * JWT payload for platform administrator access tokens.
 *
 * Platform admins operate outside tenant boundaries, so this payload omits
 * `tenantId` and `status`. The literal `type: 'platform'` discriminant ensures
 * platform tokens are never accepted by dashboard guards.
 */
export interface PlatformJwtPayload {
  /** Unique JWT ID (UUID v4) generated by TokenManagerService for revocation. */
  jti: string
  /** Subject — the platform administrator's internal identifier. */
  sub: string
  /** Administrator's platform-level role (e.g. `'super_admin'`, `'support'`). */
  role: string
  /** Discriminant literal — always `'platform'`. Prevents token type confusion. */
  type: 'platform'
  /**
   * Whether MFA (TOTP) is currently enabled on the admin's account.
   * Follows the same semantics as `DashboardJwtPayload.mfaEnabled`.
   */
  mfaEnabled: boolean
  /** Whether the admin completed MFA verification before this token was issued. */
  mfaVerified: boolean
  /**
   * The admin's token **epoch** at issuance — a per-user generation counter the server bumps to
   * invalidate every outstanding access token at once (a password reset). The guards reject a
   * token whose epoch is below the admin's stored epoch.
   *
   * Optional: a token issued before the field existed carries none, which reads as `0` and is
   * never rejected while the stored epoch is also `0` — the mechanism stays inert until the
   * first bump.
   */
  epoch?: number
  /** Issued-at timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  iat: number
  /** Expiration timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  exp: number
}

/**
 * Short-lived JWT payload issued during an MFA challenge.
 *
 * This token grants no resource access on its own. It is exchanged for a full
 * {@link DashboardJwtPayload} or {@link PlatformJwtPayload} token once the user
 * supplies a valid OTP. Default lifetime is 5 minutes.
 *
 * @remarks
 * The `context` field tells the MFA verification endpoint which full-token type
 * to issue upon successful OTP validation.
 *
 * The `jti` claim enables single-use enforcement: the issuing service must store
 * the `jti` in Redis with a TTL equal to the token's lifetime and invalidate it
 * on first successful use or explicit revocation. This prevents replay attacks
 * within the 5-minute window if the token is stolen.
 */
export interface MfaTempPayload {
  /** Unique JWT ID (UUID v4) for single-use enforcement and revocation. */
  jti: string
  /** Subject — the user or admin identifier pending MFA completion. */
  sub: string
  /** Discriminant literal — always `'mfa_challenge'`. */
  type: 'mfa_challenge'
  /** Indicates which authentication context triggered the MFA challenge. */
  context: 'dashboard' | 'platform'
  /**
   * The tenant the dashboard challenge belongs to. Present on the dashboard plane, ABSENT on the
   * platform plane — platform admins carry no tenant. It is the whole reason the challenge can
   * resolve the pending account tenant-scoped: without it the second-factor step, the
   * account-status gate and the finally-minted session all resolved the account by `sub` alone, so
   * under a host schema whose ids are per-tenant sequential a challenge could decide against, and
   * mint a session for, a homonym in another tenant.
   *
   * NOT optional in effect, despite the `?`: `verifyMfaTempToken` REJECTS a dashboard token that
   * lacks it and a platform token that carries it. The `?` only expresses that the two planes
   * populate it differently — it is never a value the caller may omit and have honoured. A missing
   * claim reads as an invalid token, not as a fall back to the pre-tenant lookup: a fallback would
   * leave the tenant-blind path reachable to anyone who simply drops the field (RFC 8725 §3.9/§3.12;
   * ASVS 6.6.2 — the out-of-band token must be bound to the request that originated it). A token
   * minted before this claim existed is therefore refused, and the user redoes login within the
   * five-minute TTL; there is no in-flight fallback to drain.
   */
  tenantId?: string
  /**
   * The subject's token **epoch** at issuance, in the plane named by `context`.
   *
   * The challenge token is a credential like any other — half of one, held by a caller who has
   * already proved the password — and it must die with the rest when the account's credentials
   * are rotated. Without this claim it did not: a password reset bumps the epoch and kills
   * every access token, but nothing touched an outstanding `mfa:` record, so a challenge token
   * minted before the reset stayed redeemable for its whole TTL and completing it issued a
   * full session under the *new* epoch. The reset is meant to end everything.
   *
   * Optional for the same reason the access-token epochs are: a token issued before the field
   * existed carries none, which reads as `0` and is never rejected while the stored epoch is
   * also `0`, so the mechanism stays inert until the first bump.
   */
  epoch?: number
  /** Issued-at timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  iat: number
  /** Expiration timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  exp: number
}
