/**
 * JWT payload type definitions for @bymax-one/nest-auth.
 *
 * Three distinct token types prevent cross-context token misuse:
 *  - DashboardJwtPayload — regular tenant users
 *  - PlatformJwtPayload  — platform administrators
 *  - MfaTempPayload      — short-lived challenge token during MFA flow
 *
 * @remarks
 * `emailVerified` is intentionally absent from all payloads; it is not a JWT
 * claim. Status fields are snapshots captured at issuance time and may diverge
 * from the database after subsequent state transitions.
 *
 * These interfaces represent the shape of a **decoded and verified** token.
 * When signing tokens, `iat` and `exp` are populated automatically by
 * `@nestjs/jwt` — do not include them in the signing payload.
 */

/**
 * JWT payload for dashboard (tenant) user access tokens.
 *
 * Issued by TokenManagerService after successful login or MFA verification.
 * The literal `type: 'dashboard'` discriminant prevents accidental acceptance
 * of platform tokens in dashboard guards and vice-versa.
 */
export interface DashboardJwtPayload {
  /** Unique JWT ID (UUID v4) generated by TokenManagerService for revocation. */
  jti: string
  /** Subject — the authenticated user's internal identifier. */
  sub: string
  /** Tenant the user belongs to; used for data isolation. */
  tenantId: string
  /** User's assigned role within the tenant (e.g. `'admin'`, `'member'`). */
  role: string
  /** Discriminant literal — always `'dashboard'`. Prevents token type confusion. */
  type: 'dashboard'
  /**
   * Snapshot of the user's account status at token issuance time.
   * May diverge from the current database value after status changes.
   * The library re-validates status against a Redis cache on each authenticated
   * request (TTL controlled by `userStatusCacheTtlSeconds` in module options).
   */
  status: string
  /**
   * Whether MFA (TOTP) is currently enabled on the user's account.
   *
   * Stamped at token issuance. When `true`, the `MfaRequiredGuard` enforces that
   * `mfaVerified` is also `true` before granting access to protected resources.
   * Resets to `false` on token rotation (the Redis session does not persist this
   * state) — this is intentional: MFA enable/disable always invalidates all sessions.
   */
  mfaEnabled: boolean
  /** Whether the user completed MFA verification before this token was issued. */
  mfaVerified: boolean
  /** Issued-at timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  iat: number
  /** Expiration timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  exp: number
}

/**
 * JWT payload for platform administrator access tokens.
 *
 * Platform admins operate outside tenant boundaries, so this payload omits
 * `tenantId` and `status`. The literal `type: 'platform'` discriminant ensures
 * platform tokens are never accepted by dashboard guards.
 */
export interface PlatformJwtPayload {
  /** Unique JWT ID (UUID v4) generated by TokenManagerService for revocation. */
  jti: string
  /** Subject — the platform administrator's internal identifier. */
  sub: string
  /** Administrator's platform-level role (e.g. `'super_admin'`, `'support'`). */
  role: string
  /** Discriminant literal — always `'platform'`. Prevents token type confusion. */
  type: 'platform'
  /**
   * Whether MFA (TOTP) is currently enabled on the admin's account.
   * Follows the same semantics as `DashboardJwtPayload.mfaEnabled`.
   */
  mfaEnabled: boolean
  /** Whether the admin completed MFA verification before this token was issued. */
  mfaVerified: boolean
  /** Issued-at timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  iat: number
  /** Expiration timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  exp: number
}

/**
 * Short-lived JWT payload issued during an MFA challenge step.
 *
 * This token grants no resource access on its own. It is exchanged for a full
 * {@link DashboardJwtPayload} or {@link PlatformJwtPayload} token once the user
 * supplies a valid OTP. Default lifetime is 5 minutes.
 *
 * @remarks
 * The `context` field tells the MFA verification endpoint which full-token type
 * to issue upon successful OTP validation.
 *
 * The `jti` claim enables single-use enforcement: the issuing service must store
 * the `jti` in Redis with a TTL equal to the token's lifetime and invalidate it
 * on first successful use or explicit revocation. This prevents replay attacks
 * within the 5-minute window if the token is stolen.
 */
export interface MfaTempPayload {
  /** Unique JWT ID (UUID v4) for single-use enforcement and revocation. */
  jti: string
  /** Subject — the user or admin identifier pending MFA completion. */
  sub: string
  /** Discriminant literal — always `'mfa_challenge'`. */
  type: 'mfa_challenge'
  /** Indicates which authentication context triggered the MFA challenge. */
  context: 'dashboard' | 'platform'
  /** Issued-at timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  iat: number
  /** Expiration timestamp (Unix seconds). Populated automatically by `@nestjs/jwt`. */
  exp: number
}
