/**
 * OAuth provider plugin contract for @bymax-one/nest-auth.
 *
 * Providers implement the OAuth 2.0 Authorization Code flow natively using the
 * Node.js built-in `fetch` API — no Passport.js or third-party OAuth libraries
 * are used or permitted.
 *
 * @remarks
 * The plugin pattern allows new providers (Google, GitHub, GitLab, etc.) to be
 * registered without modifying the core auth module. Each plugin is responsible
 * for its own authorize URL construction, code exchange, and profile normalization.
 */

/**
 * Normalized user profile returned by any OAuth provider after a successful
 * code exchange and profile fetch.
 *
 * @remarks
 * The `provider` + `providerId` pair forms a stable, unique identity across
 * login sessions and is used to link OAuth accounts to internal user records.
 */
export interface OAuthProfile {
  /** Identifier for the OAuth provider (e.g. `'google'`, `'github'`). */
  provider: string
  /**
   * The user's unique identifier within the provider's system.
   * Must be treated as an opaque string — do not assume numeric or UUID format.
   */
  providerId: string
  /** Primary email address returned by the provider. */
  email: string
  /**
   * Display name returned by the provider, if available.
   *
   * @remarks
   * When absent, the consuming service layer must supply a fallback (e.g. the
   * local part of the email address) before creating a user via `createWithOAuth`,
   * because `CreateWithOAuthData.name` is required.
   */
  name?: string
  /** URL to the user's avatar/profile picture, if available. */
  avatar?: string
}

/**
 * Contract for OAuth 2.0 Authorization Code flow plugins.
 *
 * Implement this interface to add a new OAuth provider. The plugin is
 * responsible for all three steps of the flow:
 *  1. Constructing the provider's authorization URL (with a CSRF-protection state value).
 *  2. Exchanging the authorization code for an access token.
 *  3. Fetching and normalizing the user profile.
 *
 * @example
 * ```typescript
 * class GoogleOAuthPlugin implements OAuthProviderPlugin {
 *   readonly name = 'google'
 *
 *   authorizeUrl(state: string): string { ... }
 *   async exchangeCode(code: string): Promise<{ access_token: string; token_type: string }> { ... }
 *   async fetchProfile(accessToken: string): Promise<OAuthProfile> { ... }
 * }
 * ```
 */
export interface OAuthProviderPlugin {
  /**
   * Unique, stable provider name used as a route segment and storage key.
   * Must be lowercase and URL-safe (e.g. `'google'`, `'github'`).
   */
  name: string

  /**
   * Constructs the provider's OAuth 2.0 authorization URL.
   *
   * @param state - Anti-CSRF nonce generated by the auth service. Must be
   *   included in the URL as the `state` query parameter and validated on
   *   the callback to prevent CSRF attacks.
   * @param codeChallenge - Optional PKCE `code_challenge` (RFC 7636). When
   *   the OAuthService supplies this value, the plugin MUST include it in
   *   the authorize URL as `code_challenge` + `code_challenge_method=S256`.
   *   The matching `code_verifier` is persisted server-side by OAuthService
   *   and passed back to {@link exchangeCode} on callback.
   *
   *   Plugins whose providers do not support PKCE may ignore the parameter;
   *   the OAuthService will not fail when it is absent from the resulting
   *   URL, but support is strongly recommended for any provider that
   *   implements RFC 7636.
   *
   * @returns The full authorization URL to redirect the user to.
   */
  authorizeUrl(state: string, codeChallenge?: string): string

  /**
   * Exchanges an authorization code for an access token.
   *
   * @remarks
   * Never log or persist the `access_token` returned by this method.
   * Pass it directly to {@link fetchProfile} and discard it after use.
   *
   * @param code - The authorization code received on the OAuth callback.
   * @param codeVerifier - Optional PKCE `code_verifier` (RFC 7636). Required
   *   when the plugin included a `code_challenge` in {@link authorizeUrl}.
   *   The plugin MUST forward this value to the provider's token endpoint.
   * @returns A standard OAuth 2.0 token response containing at minimum
   *   `access_token` and `token_type`. Implementations should validate that
   *   `token_type` is `'Bearer'` before using the token.
   */
  exchangeCode(
    code: string,
    codeVerifier?: string
  ): Promise<{
    access_token: string
    token_type: string
    expires_in?: number
    scope?: string
  }>

  /**
   * Fetches and normalizes the authenticated user's profile from the provider.
   *
   * @remarks
   * Never log or persist the `accessToken` parameter.
   *
   * @param accessToken - The access token obtained from {@link exchangeCode}.
   *   Treat as a short-lived secret — do not store or forward to other services.
   * @returns A normalized {@link OAuthProfile} for account linking.
   */
  fetchProfile(accessToken: string): Promise<OAuthProfile>
}
