/**
 * AuthPlatformUser type and IPlatformUserRepository interface for @bymax-one/nest-auth.
 *
 * Defines the canonical shape of a platform administrator and the repository
 * contract that must be implemented by the consuming application. Platform
 * admins are scoped to the operator layer — above tenants — and always have
 * a local password credential.
 */

/**
 * Represents the authenticated record for a platform administrator.
 *
 * @remarks
 * Platform administrators operate at the operator/super-admin level, separate
 * from tenant users. They always have a local password and do not use OAuth.
 * MFA fields are encrypted/hashed identically to the dashboard user flow.
 *
 * Notable differences from {@link AuthUser}:
 * - `passwordHash` is non-nullable — platform admins always have a local credential.
 * - `emailVerified` is absent — platform admin accounts are provisioned directly
 *   by operators and do not go through an email-verification flow.
 * - `updatedAt` is present to support audit and cache-invalidation requirements
 *   at the operator level.
 */
export interface AuthPlatformUser {
  /** Unique internal identifier for the platform administrator (UUID or similar). */
  id: string

  /** Platform administrator's primary email address. Used for login. */
  email: string

  /** Display name of the platform administrator. */
  name: string

  /**
   * scrypt hash of the platform administrator's password, generated by PasswordService.
   * Platform admins always have a local password — this field is never null.
   * Never store or receive a plaintext password.
   */
  passwordHash: string

  /** Authorization role within the platform layer (e.g. 'super-admin', 'support'). */
  role: string

  /** Account lifecycle status (e.g. 'active', 'suspended'). Application-defined. */
  status: string

  /** Whether Time-based One-Time Password (TOTP) MFA is currently enabled. */
  mfaEnabled: boolean

  /**
   * TOTP shared secret for MFA verification.
   * Stored encrypted with AES-256-GCM before persisting. Decrypt only when needed.
   * Absent when MFA has never been configured.
   */
  mfaSecret?: string

  /**
   * One-time recovery codes that allow bypassing TOTP.
   * Hashed with SHA-256 before storing. Compare using timingSafeEqual — never ===.
   * Absent when MFA has never been configured.
   */
  mfaRecoveryCodes?: string[]

  /**
   * Logical platform identifier for multi-platform deployments.
   * Absent in single-platform configurations.
   */
  platformId?: string

  /** Timestamp of the administrator's most recent successful login, or null if never logged in. */
  lastLoginAt: Date | null

  /** Timestamp when the record was last modified. */
  updatedAt: Date

  /** Timestamp when the platform administrator record was created. */
  createdAt: Date
}

/**
 * A safe projection of {@link AuthPlatformUser} that omits credential and secret fields.
 *
 * Use this type wherever platform admin data is returned to callers, passed to hooks,
 * or included in API responses. It is a compile-time guarantee that
 * `passwordHash`, `mfaSecret`, and `mfaRecoveryCodes` are not inadvertently
 * serialized or forwarded to consumers who have no business accessing them.
 */
export type SafeAuthPlatformUser = Omit<
  AuthPlatformUser,
  'passwordHash' | 'mfaSecret' | 'mfaRecoveryCodes'
>

/**
 * Data required to update a platform administrator's TOTP MFA configuration.
 *
 * @remarks
 * Pass `null` to `mfaSecret` and `mfaRecoveryCodes` to disable and clear MFA.
 */
export interface UpdatePlatformMfaData {
  /** New MFA enabled state. */
  mfaEnabled: boolean

  /**
   * AES-256-GCM encrypted TOTP secret, or null to clear it.
   */
  mfaSecret: string | null

  /**
   * SHA-256 hashed recovery codes, or null to clear them.
   */
  mfaRecoveryCodes: string[] | null
}

/**
 * Repository contract for platform administrator persistence.
 *
 * @remarks
 * The consuming application must implement this interface and provide it via
 * the NestAuthModule configuration (`platformUserRepository` option). The
 * library never imports a concrete ORM model — all persistence is delegated
 * here. Use a Symbol injection token when binding this interface in NestJS.
 *
 * @example
 * ```typescript
 * export const PLATFORM_USER_REPOSITORY = Symbol('IPlatformUserRepository')
 *
 * // In your module:
 * { provide: PLATFORM_USER_REPOSITORY, useClass: PrismaPlatformUserRepository }
 * ```
 */
export interface IPlatformUserRepository {
  /**
   * Finds a platform administrator by their internal unique identifier.
   *
   * @param id - The platform administrator's unique identifier.
   * @returns The matching record, or null if not found.
   */
  findById(id: string): Promise<AuthPlatformUser | null>

  /**
   * Finds a platform administrator by their email address.
   *
   * @remarks
   * Used during the login flow to locate the account before verifying the
   * password. Email comparison should be case-insensitive.
   *
   * @param email - The platform administrator's email address.
   * @returns The matching record, or null if not found.
   */
  findByEmail(email: string): Promise<AuthPlatformUser | null>

  /**
   * Records the current timestamp as the administrator's last successful login time.
   *
   * @remarks
   * Call this after a successful credential verification and before issuing tokens
   * to keep the audit trail accurate.
   *
   * @param id - The platform administrator's unique identifier.
   */
  updateLastLogin(id: string): Promise<void>

  /**
   * Updates the platform administrator's TOTP MFA configuration.
   *
   * @remarks
   * Used during MFA enrollment and revocation flows. The caller must encrypt
   * `mfaSecret` with AES-256-GCM and hash `mfaRecoveryCodes` with SHA-256
   * before passing them here.
   *
   * @param id - The platform administrator's unique identifier.
   * @param data - New MFA state. See {@link UpdatePlatformMfaData}.
   */
  updateMfa(id: string, data: UpdatePlatformMfaData): Promise<void>

  /**
   * Replaces the platform administrator's stored password hash.
   *
   * @remarks
   * The caller must generate `passwordHash` via PasswordService — never pass
   * a plaintext password to this method.
   *
   * @param id - The platform administrator's unique identifier.
   * @param passwordHash - New hash generated by PasswordService.
   */
  updatePassword(id: string, passwordHash: string): Promise<void>

  /**
   * Updates the platform administrator's account lifecycle status.
   *
   * @remarks
   * Used by operator-level administration flows to suspend or reactivate
   * platform admin accounts.
   *
   * @param id - The platform administrator's unique identifier.
   * @param status - New status value (e.g. 'active', 'suspended').
   */
  updateStatus(id: string, status: string): Promise<void>
}
