/**
 * AuthUser type and IUserRepository interface for @bymax-one/nest-auth.
 *
 * Defines the canonical shape of a dashboard/tenant user and the repository
 * contract that must be implemented by the consuming application. The library
 * never imports a concrete ORM model — only this interface.
 *
 * @layer Interface
 */

/**
 * Represents the authenticated user record for a dashboard/tenant user.
 *
 * @remarks
 * This type is returned by all authentication operations and stored (without
 * sensitive fields) inside JWT access token payloads. The consuming application
 * must persist these fields in its own user table and implement
 * {@link IUserRepository} to bridge the gap.
 */
export interface AuthUser {
  /** Unique internal identifier for the user (UUID or similar). */
  id: string

  /** User's primary email address. Used for login and email verification. */
  email: string

  /** Display name of the user. */
  name: string

  /**
   * scrypt hash of the user's password, generated by PasswordService.
   * null for OAuth-only users who have never set a local password.
   * Never receive or store a plaintext password — only a hash generated by PasswordService.
   */
  passwordHash: string | null

  /** Authorization role (e.g. 'admin', 'member', 'viewer'). Application-defined. */
  role: string

  /** Account lifecycle status (e.g. 'active', 'suspended', 'pending'). Application-defined. */
  status: string

  /** Tenant identifier that scopes the user to a specific organization. */
  tenantId: string

  /** Whether the user's email address has been verified via the verification flow. */
  emailVerified: boolean

  /** Whether Time-based One-Time Password (TOTP) MFA is currently enabled. */
  mfaEnabled: boolean

  /**
   * TOTP shared secret for MFA verification.
   * Stored encrypted with AES-256-GCM before persisting. Decrypt only when needed.
   * Absent when MFA has never been configured.
   */
  mfaSecret?: string

  /**
   * One-time recovery codes that allow the user to bypass TOTP.
   * Hashed with SHA-256 before storing. Compare using timingSafeEqual — never ===.
   * Absent when MFA has never been configured.
   */
  mfaRecoveryCodes?: string[]

  /**
   * Primary OAuth provider identifier (e.g. 'google', 'github').
   * Absent for local-only accounts.
   */
  oauthProvider?: string

  /**
   * User's unique identifier within the OAuth provider's system.
   * Absent for local-only accounts.
   */
  oauthProviderId?: string

  /** Timestamp of the user's most recent successful login, or null if never logged in. */
  lastLoginAt: Date | null

  /** Timestamp when the user record was created. */
  createdAt: Date
}

/**
 * A safe projection of {@link AuthUser} that omits credential and secret fields.
 *
 * Use this type wherever user data is returned to callers, passed to hooks,
 * or included in API responses. It is a compile-time guarantee that
 * `passwordHash`, `mfaSecret`, and `mfaRecoveryCodes` are not inadvertently
 * serialized or forwarded to consumers who have no business accessing them.
 */
export type SafeAuthUser = Omit<AuthUser, 'passwordHash' | 'mfaSecret' | 'mfaRecoveryCodes'>

/**
 * Data required to create a new local (email + password) user.
 *
 * @remarks
 * `passwordHash` must be the hash produced by PasswordService — never a
 * plaintext password. Pass `null` when creating an OAuth-only account that
 * does not yet have a local password set.
 */
export interface CreateUserData {
  /** User's primary email address. Must be unique within the tenant. */
  email: string

  /** Display name of the user. */
  name: string

  /**
   * Hashed password generated by PasswordService.
   * null for OAuth-only users who have no local password.
   * Never receive or store plaintext passwords.
   */
  passwordHash: string | null

  /** Authorization role. Defaults to the application-defined base role when omitted. */
  role?: string

  /** Account lifecycle status. Defaults to 'pending' when omitted. */
  status?: string

  /** Tenant identifier that scopes the user record. */
  tenantId: string

  /** Whether the email should be marked as verified at creation time. Defaults to false. */
  emailVerified?: boolean
}

/**
 * Data required to update a user's TOTP MFA configuration.
 *
 * @remarks
 * Pass `null` to `mfaSecret` and `mfaRecoveryCodes` to disable and clear MFA.
 */
export interface UpdateMfaData {
  /** New MFA enabled state. */
  mfaEnabled: boolean

  /**
   * AES-256-GCM encrypted TOTP secret, or null to clear it.
   */
  mfaSecret: string | null

  /**
   * SHA-256 hashed recovery codes, or null to clear them.
   */
  mfaRecoveryCodes: string[] | null
}

/**
 * Data required to create a new user via an OAuth provider.
 *
 * @remarks
 * Users created through this path have no local password (`passwordHash` is
 * implicitly null). A local password may be added later via `updatePassword`.
 */
export interface CreateWithOAuthData {
  /** User's primary email address sourced from the OAuth provider. */
  email: string

  /** Display name sourced from the OAuth provider profile. */
  name: string

  /** Authorization role. Defaults to the application-defined base role when omitted. */
  role?: string

  /** Account lifecycle status. Defaults to 'active' when omitted. */
  status?: string

  /** Tenant identifier that scopes the user record. */
  tenantId: string

  /**
   * Whether the email is pre-verified by the OAuth provider.
   * Set to true when the provider guarantees verified email addresses.
   */
  emailVerified?: boolean

  /** OAuth provider identifier (e.g. 'google', 'github'). */
  oauthProvider: string

  /** User's unique identifier within the OAuth provider's system. */
  oauthProviderId: string
}

/**
 * Names one account on the dashboard plane: the id, and the tenant it belongs to.
 *
 * The base every tenant-scoped port parameter extends. It exists because the two fields must
 * travel together — an id without its tenant is not an account on this plane, since the library
 * may not assume ids are unique across tenants.
 *
 * **Why an object and not two positional strings.** A positional pair cannot make a stale
 * implementation fail. TypeScript's structural typing accepts an implementation with FEWER
 * parameters, so a consumer's pre-upgrade `findById(id)` satisfied a `findById(id, tenantId)`
 * signature and silently ignored the tenant — the scoping this port exists to require simply did
 * not bind, on a clean build. Worse on the writes: the library called
 * `updatePassword(id, tenantId, hash)` and a stale two-parameter implementation bound
 * `passwordHash = tenantId`, writing the tenant id into the credential column.
 *
 * An object parameter is structurally INCOMPATIBLE with the old shape, so the same implementation
 * now fails to compile. That property is the whole reason for the shape; `tenant-scoped-port`
 * pins it with a type test, because it is invisible in the signature itself.
 *
 * One residual hole, stated rather than hidden, and stated narrowly: TypeScript always accepts an
 * implementation taking NO parameters. What the object shape buys is only that a value cannot be
 * bound into the wrong positional slot — it says nothing about what the body then does. A
 * zero-parameter implementation still compiles and can read or write whatever it likes, unscoped,
 * exactly as a parameterised one that ignores its argument can.
 *
 * This shape closes a defect the compiler can see. Whether an implementation actually filters on
 * the tenant is a claim only that implementation can honour, and this port states it as a MUST on
 * every method rather than pretending to enforce it.
 */
export interface TenantScopedUserRef {
  /** The user's unique identifier. */
  id: string
  /** The tenant the account belongs to. Every read and write MUST be scoped to it. */
  tenantId: string
}

/** Locates one account by email inside a tenant. */
export interface FindUserByEmailParams {
  /** The user's email address (case-insensitive recommended). */
  email: string
  /** Tenant scope. Prevents cross-tenant email collisions. */
  tenantId: string
}

/** Replaces one account's stored password hash. */
export interface UpdatePasswordParams extends TenantScopedUserRef {
  /** New hash generated by `PasswordService`. Never plaintext. */
  passwordHash: string
}

/** Rewrites one account's TOTP MFA configuration. */
export interface UpdateMfaParams extends TenantScopedUserRef {
  /** The MFA fields to write. See {@link UpdateMfaData}. */
  data: UpdateMfaData
}

/** Sets one account's authorization status. */
export interface UpdateStatusParams extends TenantScopedUserRef {
  /** New status value, in the host's own vocabulary. */
  status: string
}

/** Sets whether one account's address has been verified. */
export interface UpdateEmailVerifiedParams extends TenantScopedUserRef {
  /** Whether the address is now verified. */
  verified: boolean
}

/** Moves one account to a new address. */
export interface UpdateEmailParams extends TenantScopedUserRef {
  /** The new address, already normalized by the caller. */
  email: string
}

/** Locates one account by an external identity inside a tenant. */
export interface FindUserByOAuthIdParams {
  /** OAuth provider key (e.g. `'google'`). */
  provider: string
  /** The provider's own subject identifier for the user. */
  providerId: string
  /** Tenant scope. */
  tenantId: string
}

/** Attaches an external identity to an existing account. */
export interface LinkOAuthParams extends TenantScopedUserRef {
  /** OAuth provider key (e.g. `'google'`). */
  provider: string
  /** The provider's own subject identifier for the user. */
  providerId: string
}

/**
 * Repository contract for dashboard/tenant user persistence.
 *
 * @remarks
 * The consuming application must implement this interface and provide it via
 * the NestAuthModule configuration (`userRepository` option). The library
 * never imports a concrete ORM model — all persistence is delegated here.
 * Use a Symbol injection token when binding this interface in NestJS.
 *
 * @example
 * ```typescript
 * export const USER_REPOSITORY = Symbol('IUserRepository')
 *
 * // In your module:
 * { provide: USER_REPOSITORY, useClass: PrismaUserRepository }
 * ```
 */
export interface IUserRepository {
  /**
   * Finds a user by their internal unique identifier.
   *
   * @remarks
   * The tenant is REQUIRED, not an option the caller may skip. This library may not assume the
   * consumer's ids are unique across tenants — a host that numbers users per tenant gives every
   * tenant a user `1` — so a lookup by bare id can answer with another tenant's row. The optional
   * form was worse than no scoping at all: it read as a decision the caller had made, while every
   * one of this library's own twelve call sites omitted it, none of them a cross-tenant flow.
   *
   * A deployment that genuinely wants a cross-tenant read owns the repository and can write that
   * query itself; it does not need this port to leave the door open for it.
   *
   * @returns The matching user record, or null if not found.
   */
  findById(params: TenantScopedUserRef): Promise<AuthUser | null>

  /**
   * Finds a user by email address within a specific tenant.
   *
   * @returns The matching user record, or null if not found.
   */
  findByEmail(params: FindUserByEmailParams): Promise<AuthUser | null>

  /**
   * Creates a new user record with a local (email + password) credential.
   *
   * @remarks
   * The `passwordHash` field must be a hash generated by PasswordService.
   * Never receive or store a plaintext password.
   *
   * @param data - Creation payload. See {@link CreateUserData}.
   * @returns The newly created user record with all fields populated.
   */
  create(data: CreateUserData): Promise<AuthUser>

  /**
   * Replaces the user's stored password hash.
   *
   *
   * The tenant is required for the same reason {@link findById} takes one: this library may not
   * assume the consumer's ids are unique across tenants — `findById` takes a tenant precisely
   * because they may not be, and a host that numbers users per tenant gives every tenant a user
   * `1`. A write keyed by id alone can land on another tenant's row. An implementation MUST scope
   * the update by both the id and the tenant, exactly as its read does.
   *
   * @param params - See {@link UpdatePasswordParams}.
   */
  updatePassword(params: UpdatePasswordParams): Promise<void>

  /**
   * Updates the user's TOTP MFA configuration.
   *
   * The tenant is required for the same reason {@link findById} takes one: the library may not
   * assume ids are unique across tenants, so a write keyed by id alone can land on another tenant's
   * row — or on a row other than the one the MFA flow read a moment earlier, which would leave a
   * spent recovery code in the account's list. An implementation MUST scope the update by both the
   * id and the tenant, exactly as its read does.
   *
   * @param params - See {@link UpdateMfaParams}.
   */
  updateMfa(params: UpdateMfaParams): Promise<void>

  /**
   * Records the current timestamp as the user's last successful login time.
   *
   *
   * The tenant is required for the same reason {@link findById} takes one: this library may not
   * assume the consumer's ids are unique across tenants — `findById` takes a tenant precisely
   * because they may not be, and a host that numbers users per tenant gives every tenant a user
   * `1`. A write keyed by id alone can land on another tenant's row. An implementation MUST scope
   * the update by both the id and the tenant, exactly as its read does.
   *
   * @param params - See {@link TenantScopedUserRef}.
   */
  updateLastLogin(params: TenantScopedUserRef): Promise<void>

  /**
   * Updates the user's account lifecycle status.
   *
   *
   * The tenant is required for the same reason {@link findById} takes one: this library may not
   * assume the consumer's ids are unique across tenants — `findById` takes a tenant precisely
   * because they may not be, and a host that numbers users per tenant gives every tenant a user
   * `1`. A write keyed by id alone can land on another tenant's row. An implementation MUST scope
   * the update by both the id and the tenant, exactly as its read does.
   *
   * @param params - See {@link UpdateStatusParams}.
   */
  updateStatus(params: UpdateStatusParams): Promise<void>

  /**
   * Marks the user's email address as verified or unverified.
   *
   *
   * The tenant is required for the same reason {@link findById} takes one: this library may not
   * assume the consumer's ids are unique across tenants — `findById` takes a tenant precisely
   * because they may not be, and a host that numbers users per tenant gives every tenant a user
   * `1`. A write keyed by id alone can land on another tenant's row. An implementation MUST scope
   * the update by both the id and the tenant, exactly as its read does.
   *
   * @param params - See {@link UpdateEmailVerifiedParams}.
   */
  updateEmailVerified(params: UpdateEmailVerifiedParams): Promise<void>

  /**
   * Replaces the account's email address.
   *
   * Called only after the new address has been proven — a token mailed to it and nothing
   * else has come back — so the account stays verified across the change. An implementation
   * that also clears its own verification flag would sign the user out of a state they just
   * proved.
   *
   * The uniqueness of `email` within the tenant is checked by the caller immediately before
   * this runs, but a unique index on `(tenantId, email)` is still the right thing to have:
   * the check and this write are not one transaction, and the index is what makes the race
   * a failed write instead of two accounts sharing a recovery address.
   *
   *
   * The tenant is required for the same reason {@link findById} takes one: this library may not
   * assume the consumer's ids are unique across tenants — `findById` takes a tenant precisely
   * because they may not be, and a host that numbers users per tenant gives every tenant a user
   * `1`. A write keyed by id alone can land on another tenant's row. An implementation MUST scope
   * the update by both the id and the tenant, exactly as its read does.
   *
   * @throws Whatever the implementation throws when the address is taken.
   */
  updateEmail(params: UpdateEmailParams): Promise<void>

  /**
   * Finds a user by their OAuth provider and external provider user ID.
   *
   * @remarks
   * Required to prevent duplicate account creation when the same OAuth identity
   * authenticates multiple times. Always query by both `provider` and `providerId`
   * to avoid cross-provider ID collisions.
   *
   * @returns The matching user record, or null if not found.
   */
  findByOAuthId(params: FindUserByOAuthIdParams): Promise<AuthUser | null>

  /**
   * Links an existing user account to an OAuth provider identity.
   *
   *
   * The tenant is required for the same reason {@link findById} takes one: this library may not
   * assume the consumer's ids are unique across tenants — `findById` takes a tenant precisely
   * because they may not be, and a host that numbers users per tenant gives every tenant a user
   * `1`. A write keyed by id alone can land on another tenant's row. An implementation MUST scope
   * the update by both the id and the tenant, exactly as its read does.
   *
   * @param params - See {@link LinkOAuthParams}.
   */
  linkOAuth(params: LinkOAuthParams): Promise<void>

  /**
   * Creates a new user record originating from an OAuth provider.
   *
   * @remarks
   * Users created via this path have no local password. A password may be
   * set later via {@link updatePassword}.
   *
   * @param data - OAuth creation payload. See {@link CreateWithOAuthData}.
   * @returns The newly created user record with all fields populated.
   */
  createWithOAuth(data: CreateWithOAuthData): Promise<AuthUser>
}
