/**
 * AuthUser type and IUserRepository interface for @bymax-one/nest-auth.
 *
 * Defines the canonical shape of a dashboard/tenant user and the repository
 * contract that must be implemented by the consuming application. The library
 * never imports a concrete ORM model — only this interface.
 */

/**
 * Represents the authenticated user record for a dashboard/tenant user.
 *
 * @remarks
 * This type is returned by all authentication operations and stored (without
 * sensitive fields) inside JWT access token payloads. The consuming application
 * must persist these fields in its own user table and implement
 * {@link IUserRepository} to bridge the gap.
 */
export interface AuthUser {
  /** Unique internal identifier for the user (UUID or similar). */
  id: string

  /** User's primary email address. Used for login and email verification. */
  email: string

  /** Display name of the user. */
  name: string

  /**
   * scrypt hash of the user's password, generated by PasswordService.
   * null for OAuth-only users who have never set a local password.
   * Never receive or store a plaintext password — only a hash generated by PasswordService.
   */
  passwordHash: string | null

  /** Authorization role (e.g. 'admin', 'member', 'viewer'). Application-defined. */
  role: string

  /** Account lifecycle status (e.g. 'active', 'suspended', 'pending'). Application-defined. */
  status: string

  /** Tenant identifier that scopes the user to a specific organization. */
  tenantId: string

  /** Whether the user's email address has been verified via the verification flow. */
  emailVerified: boolean

  /** Whether Time-based One-Time Password (TOTP) MFA is currently enabled. */
  mfaEnabled: boolean

  /**
   * TOTP shared secret for MFA verification.
   * Stored encrypted with AES-256-GCM before persisting. Decrypt only when needed.
   * Absent when MFA has never been configured.
   */
  mfaSecret?: string

  /**
   * One-time recovery codes that allow the user to bypass TOTP.
   * Hashed with SHA-256 before storing. Compare using timingSafeEqual — never ===.
   * Absent when MFA has never been configured.
   */
  mfaRecoveryCodes?: string[]

  /**
   * Primary OAuth provider identifier (e.g. 'google', 'github').
   * Absent for local-only accounts.
   */
  oauthProvider?: string

  /**
   * User's unique identifier within the OAuth provider's system.
   * Absent for local-only accounts.
   */
  oauthProviderId?: string

  /** Timestamp of the user's most recent successful login, or null if never logged in. */
  lastLoginAt: Date | null

  /** Timestamp when the user record was created. */
  createdAt: Date
}

/**
 * A safe projection of {@link AuthUser} that omits credential and secret fields.
 *
 * Use this type wherever user data is returned to callers, passed to hooks,
 * or included in API responses. It is a compile-time guarantee that
 * `passwordHash`, `mfaSecret`, and `mfaRecoveryCodes` are not inadvertently
 * serialized or forwarded to consumers who have no business accessing them.
 */
export type SafeAuthUser = Omit<AuthUser, 'passwordHash' | 'mfaSecret' | 'mfaRecoveryCodes'>

/**
 * Data required to create a new local (email + password) user.
 *
 * @remarks
 * `passwordHash` must be the hash produced by PasswordService — never a
 * plaintext password. Pass `null` when creating an OAuth-only account that
 * does not yet have a local password set.
 */
export interface CreateUserData {
  /** User's primary email address. Must be unique within the tenant. */
  email: string

  /** Display name of the user. */
  name: string

  /**
   * Hashed password generated by PasswordService.
   * null for OAuth-only users who have no local password.
   * Never receive or store plaintext passwords.
   */
  passwordHash: string | null

  /** Authorization role. Defaults to the application-defined base role when omitted. */
  role?: string

  /** Account lifecycle status. Defaults to 'pending' when omitted. */
  status?: string

  /** Tenant identifier that scopes the user record. */
  tenantId: string

  /** Whether the email should be marked as verified at creation time. Defaults to false. */
  emailVerified?: boolean
}

/**
 * Data required to update a user's TOTP MFA configuration.
 *
 * @remarks
 * Pass `null` to `mfaSecret` and `mfaRecoveryCodes` to disable and clear MFA.
 */
export interface UpdateMfaData {
  /** New MFA enabled state. */
  mfaEnabled: boolean

  /**
   * AES-256-GCM encrypted TOTP secret, or null to clear it.
   */
  mfaSecret: string | null

  /**
   * SHA-256 hashed recovery codes, or null to clear them.
   */
  mfaRecoveryCodes: string[] | null
}

/**
 * Data required to create a new user via an OAuth provider.
 *
 * @remarks
 * Users created through this path have no local password (`passwordHash` is
 * implicitly null). A local password may be added later via `updatePassword`.
 */
export interface CreateWithOAuthData {
  /** User's primary email address sourced from the OAuth provider. */
  email: string

  /** Display name sourced from the OAuth provider profile. */
  name: string

  /** Authorization role. Defaults to the application-defined base role when omitted. */
  role?: string

  /** Account lifecycle status. Defaults to 'active' when omitted. */
  status?: string

  /** Tenant identifier that scopes the user record. */
  tenantId: string

  /**
   * Whether the email is pre-verified by the OAuth provider.
   * Set to true when the provider guarantees verified email addresses.
   */
  emailVerified?: boolean

  /** OAuth provider identifier (e.g. 'google', 'github'). */
  oauthProvider: string

  /** User's unique identifier within the OAuth provider's system. */
  oauthProviderId: string
}

/**
 * Repository contract for dashboard/tenant user persistence.
 *
 * @remarks
 * The consuming application must implement this interface and provide it via
 * the NestAuthModule configuration (`userRepository` option). The library
 * never imports a concrete ORM model — all persistence is delegated here.
 * Use a Symbol injection token when binding this interface in NestJS.
 *
 * @example
 * ```typescript
 * export const USER_REPOSITORY = Symbol('IUserRepository')
 *
 * // In your module:
 * { provide: USER_REPOSITORY, useClass: PrismaUserRepository }
 * ```
 */
export interface IUserRepository {
  /**
   * Finds a user by their internal unique identifier.
   *
   * @param id - The user's unique identifier.
   * @param tenantId - Optional tenant scope. When provided, the result must
   *   belong to that tenant; return null otherwise. Omit only in internal
   *   admin flows where cross-tenant access is intentional and authorized.
   * @returns The matching user record, or null if not found.
   */
  findById(id: string, tenantId?: string): Promise<AuthUser | null>

  /**
   * Finds a user by email address within a specific tenant.
   *
   * @param email - The user's email address (case-insensitive recommended).
   * @param tenantId - Tenant scope. Prevents cross-tenant email collisions.
   * @returns The matching user record, or null if not found.
   */
  findByEmail(email: string, tenantId: string): Promise<AuthUser | null>

  /**
   * Creates a new user record with a local (email + password) credential.
   *
   * @remarks
   * The `passwordHash` field must be a hash generated by PasswordService.
   * Never receive or store a plaintext password.
   *
   * @param data - Creation payload. See {@link CreateUserData}.
   * @returns The newly created user record with all fields populated.
   */
  create(data: CreateUserData): Promise<AuthUser>

  /**
   * Replaces the user's stored password hash.
   *
   * @param id - The user's unique identifier.
   * @param passwordHash - New hash generated by PasswordService. Never plaintext.
   */
  updatePassword(id: string, passwordHash: string): Promise<void>

  /**
   * Updates the user's TOTP MFA configuration.
   *
   * @param id - The user's unique identifier.
   * @param data - New MFA state. See {@link UpdateMfaData}.
   */
  updateMfa(id: string, data: UpdateMfaData): Promise<void>

  /**
   * Records the current timestamp as the user's last successful login time.
   *
   * @param id - The user's unique identifier.
   */
  updateLastLogin(id: string): Promise<void>

  /**
   * Updates the user's account lifecycle status.
   *
   * @param id - The user's unique identifier.
   * @param status - New status value (e.g. 'active', 'suspended').
   */
  updateStatus(id: string, status: string): Promise<void>

  /**
   * Marks the user's email address as verified or unverified.
   *
   * @param id - The user's unique identifier.
   * @param verified - True to mark as verified, false to revoke verification.
   */
  updateEmailVerified(id: string, verified: boolean): Promise<void>

  /**
   * Finds a user by their OAuth provider and external provider user ID.
   *
   * @remarks
   * Required to prevent duplicate account creation when the same OAuth identity
   * authenticates multiple times. Always query by both `provider` and `providerId`
   * to avoid cross-provider ID collisions.
   *
   * @param provider - OAuth provider identifier (e.g. 'google', 'github').
   * @param providerId - User's unique ID within the provider.
   * @param tenantId - Tenant scope to enforce isolation.
   * @returns The matching user record, or null if not found.
   */
  findByOAuthId(provider: string, providerId: string, tenantId: string): Promise<AuthUser | null>

  /**
   * Links an existing user account to an OAuth provider identity.
   *
   * @param userId - The user's unique identifier.
   * @param provider - OAuth provider identifier (e.g. 'google', 'github').
   * @param providerId - User's unique ID within the provider.
   */
  linkOAuth(userId: string, provider: string, providerId: string): Promise<void>

  /**
   * Creates a new user record originating from an OAuth provider.
   *
   * @remarks
   * Users created via this path have no local password. A password may be
   * set later via {@link updatePassword}.
   *
   * @param data - OAuth creation payload. See {@link CreateWithOAuthData}.
   * @returns The newly created user record with all fields populated.
   */
  createWithOAuth(data: CreateWithOAuthData): Promise<AuthUser>
}
