/**
 * Google OAuth 2.0 plugin for @bymax-one/nest-auth.
 *
 * Implements the {@link OAuthProviderPlugin} contract using native `fetch` (Node.js 18+
 * built-in). No Passport.js or third-party OAuth libraries are used.
 *
 * @remarks
 * Requires the following configuration fields (all three mandatory):
 * - `clientId`    — OAuth client ID from Google Cloud Console.
 * - `clientSecret` — OAuth client secret. Never log this value.
 * - `callbackUrl` — Absolute redirect URI registered in Google Cloud Console.
 *
 * Scopes default to `['openid', 'email', 'profile']`, providing email,
 * display name, and picture from Google's UserInfo endpoint.
 */

import type { OAuthProfile, OAuthProviderPlugin } from '../../interfaces/oauth-provider.interface'

/** Google OAuth 2.0 authorization endpoint. */
const GOOGLE_AUTH_URL = 'https://accounts.google.com/o/oauth2/v2/auth'

/** Google OAuth 2.0 token exchange endpoint. */
const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token'

/** Google UserInfo endpoint — returns email, name, picture, and sub. */
const GOOGLE_USERINFO_URL = 'https://www.googleapis.com/oauth2/v2/userinfo'

/** Raw shape returned by the Google UserInfo v2 endpoint. */
interface GoogleUserInfo {
  id: string
  email: string
  verified_email?: boolean
  name?: string
  picture?: string
}

/**
 * Google OAuth 2.0 Authorization Code flow plugin.
 *
 * @example
 * ```typescript
 * const plugin = new GoogleOAuthPlugin({
 *   clientId: process.env.GOOGLE_CLIENT_ID,
 *   clientSecret: process.env.GOOGLE_CLIENT_SECRET,
 *   callbackUrl: 'https://app.example.com/auth/google/callback',
 * })
 * ```
 */
export class GoogleOAuthPlugin implements OAuthProviderPlugin {
  /** Stable provider identifier used as a route segment and storage key. */
  readonly name = 'google'

  private readonly clientId: string
  private readonly clientSecret: string
  private readonly callbackUrl: string
  private readonly scope: string[]

  constructor(config: {
    clientId: string
    clientSecret: string
    callbackUrl: string
    /** OAuth scopes to request. Defaults to `['openid', 'email', 'profile']`. */
    scope?: string[]
  }) {
    this.clientId = config.clientId
    this.clientSecret = config.clientSecret
    this.callbackUrl = config.callbackUrl
    this.scope = config.scope ?? ['openid', 'email', 'profile']
  }

  /**
   * Constructs the Google OAuth 2.0 authorization URL.
   *
   * @param state - Anti-CSRF nonce generated by {@link OAuthService}. Included as the
   *   `state` query parameter and validated by {@link OAuthService.handleCallback}.
   * @returns Full authorization URL to redirect the user to.
   */
  authorizeUrl(state: string): string {
    const params = new URLSearchParams({
      client_id: this.clientId,
      redirect_uri: this.callbackUrl,
      response_type: 'code',
      scope: this.scope.join(' '),
      state
    })
    return `${GOOGLE_AUTH_URL}?${params.toString()}`
  }

  /**
   * Exchanges an authorization code for an access token.
   *
   * Sends a POST request to the Google token endpoint using the
   * `application/x-www-form-urlencoded` content type as required by RFC 6749.
   *
   * @param code - Authorization code received on the OAuth callback.
   * @returns Token response containing at minimum `access_token` and `token_type`.
   * @throws `Error` when the token exchange fails (non-2xx response from Google).
   *
   * @remarks
   * Never log the returned `access_token`. Pass it directly to {@link fetchProfile}
   * and discard after use.
   */
  async exchangeCode(code: string): Promise<{
    access_token: string
    token_type: string
    expires_in?: number
    scope?: string
  }> {
    const body = new URLSearchParams({
      code,
      client_id: this.clientId,
      client_secret: this.clientSecret,
      redirect_uri: this.callbackUrl,
      grant_type: 'authorization_code'
    })

    const response = await fetch(GOOGLE_TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
      // 10 s timeout — prevents a slow Google endpoint from holding the request open indefinitely.
      signal: AbortSignal.timeout(10_000)
    })

    if (!response.ok) {
      throw new Error(`Google token exchange failed: ${response.status}`)
    }

    const data = (await response.json()) as {
      access_token: string
      token_type: string
      expires_in?: number
      scope?: string
    }

    // Validate that the provider returned a Bearer token before using it
    // as an Authorization header value. Any other token_type (e.g. 'mac')
    // would be silently misused in the fetchProfile Authorization header.
    if (data.token_type.toLowerCase() !== 'bearer') {
      throw new Error(`Google token exchange: unexpected token_type '${data.token_type}'`)
    }

    return data
  }

  /**
   * Fetches and normalizes the user's profile from Google's UserInfo endpoint.
   *
   * @param accessToken - The access token obtained from {@link exchangeCode}.
   *   Never log or persist this value.
   * @returns Normalized {@link OAuthProfile} for account linking.
   * @throws `Error` when the UserInfo request fails (non-2xx response from Google).
   */
  async fetchProfile(accessToken: string): Promise<OAuthProfile> {
    const response = await fetch(GOOGLE_USERINFO_URL, {
      headers: { Authorization: `Bearer ${accessToken}` },
      // 10 s timeout — prevents a slow UserInfo endpoint from holding the request open indefinitely.
      signal: AbortSignal.timeout(10_000)
    })

    if (!response.ok) {
      throw new Error(`Google UserInfo fetch failed: ${response.status}`)
    }

    const info = (await response.json()) as GoogleUserInfo

    // Reject profiles where Google has flagged the email as unverified.
    // In standard authorization flows Google does not issue tokens for unverified accounts,
    // but explicitly checking provides defence-in-depth against edge cases or future
    // API changes. Using strict inequality (`=== false`) so that accounts where
    // `verified_email` is absent (undefined) are allowed through, preserving
    // compatibility with legacy UserInfo v2 responses that omit the field.
    if (info.verified_email === false) {
      throw new Error('Google OAuth: email address is not verified.')
    }

    const profile: OAuthProfile = {
      provider: 'google',
      providerId: info.id,
      email: info.email
    }
    if (info.name !== undefined) profile.name = info.name
    if (info.picture !== undefined) profile.avatar = info.picture
    return profile
  }
}
