/**
 * Shared JWT payload type definitions for @bymax-one/nest-auth.
 *
 * Redeclared here (instead of re-exported from `../../server`) so that the
 * shared subpath stays free of any server-side runtime imports. The shapes
 * are kept structurally compatible with the server-side definitions in
 * `src/server/interfaces/jwt-payload.interface.ts` — any change made there
 * must be reflected here.
 *
 * @remarks
 * These interfaces describe the shape of a **decoded and verified** token.
 * `iat` and `exp` are populated automatically by the JWT signing layer on
 * the server; they are not part of the signing payload.
 */

/**
 * JWT payload for dashboard (tenant) user access tokens.
 *
 * The literal `type: 'dashboard'` discriminant prevents accidental
 * acceptance of platform tokens in dashboard-scoped checks and vice-versa.
 */
export interface DashboardJwtPayload {
  /** Unique JWT ID (UUID v4) generated by the server for revocation tracking. */
  jti: string

  /** Subject — the authenticated user's internal identifier. */
  sub: string

  /** Tenant the user belongs to; used for data isolation. */
  tenantId: string

  /** User's assigned role within the tenant (e.g. `'admin'`, `'member'`). */
  role: string

  /** Discriminant literal — always `'dashboard'`. Prevents token type confusion. */
  type: 'dashboard'

  /** Snapshot of the user's account status at token issuance time. */
  status: string

  /** Whether MFA (TOTP) is currently enabled on the user's account. */
  mfaEnabled: boolean

  /** Whether the user completed MFA verification before this token was issued. */
  mfaVerified: boolean

  /**
   * The user's token **epoch** at issuance — a per-user generation counter the server bumps
   * to invalidate every outstanding access token at once (a password reset). Verification
   * rejects a token whose epoch is below the user's stored epoch.
   *
   * Optional: a token issued before the field existed carries none, which reads as `0` and is
   * never rejected while the stored epoch is also `0` — the mechanism stays inert until the
   * first bump.
   */
  epoch?: number

  /** Issued-at timestamp (Unix seconds). */
  iat: number

  /** Expiration timestamp (Unix seconds). */
  exp: number
}

/**
 * JWT payload for platform administrator access tokens.
 *
 * Platform admins operate outside tenant boundaries, so this payload omits
 * `tenantId` and `status`. The literal `type: 'platform'` discriminant
 * ensures platform tokens are never accepted by dashboard-scoped checks.
 */
export interface PlatformJwtPayload {
  /** Unique JWT ID (UUID v4) generated by the server for revocation tracking. */
  jti: string

  /** Subject — the platform administrator's internal identifier. */
  sub: string

  /** Administrator's platform-level role (e.g. `'super_admin'`, `'support'`). */
  role: string

  /** Discriminant literal — always `'platform'`. Prevents token type confusion. */
  type: 'platform'

  /** Whether MFA (TOTP) is currently enabled on the admin's account. */
  mfaEnabled: boolean

  /** Whether the admin completed MFA verification before this token was issued. */
  mfaVerified: boolean

  /**
   * The admin's token **epoch** at issuance — a per-user generation counter the server bumps
   * to invalidate every outstanding access token at once (a password reset). Verification
   * rejects a token whose epoch is below the admin's stored epoch.
   *
   * Optional: a token issued before the field existed carries none, which reads as `0` and is
   * never rejected while the stored epoch is also `0` — the mechanism stays inert until the
   * first bump.
   */
  epoch?: number

  /** Issued-at timestamp (Unix seconds). */
  iat: number

  /** Expiration timestamp (Unix seconds). */
  exp: number
}

/**
 * Short-lived JWT payload issued during an MFA challenge.
 *
 * Grants no resource access on its own — exchanged for a full
 * {@link DashboardJwtPayload} or {@link PlatformJwtPayload} token after the
 * user supplies a valid OTP. Default lifetime is 5 minutes.
 */
export interface MfaTempPayload {
  /** Unique JWT ID (UUID v4) for single-use enforcement and revocation. */
  jti: string

  /** Subject — the user or admin identifier pending MFA completion. */
  sub: string

  /** Discriminant literal — always `'mfa_challenge'`. */
  type: 'mfa_challenge'

  /** Indicates which authentication context triggered the MFA challenge. */
  context: 'dashboard' | 'platform'

  /**
   * The tenant the dashboard challenge belongs to. Present on the dashboard plane, absent on the
   * platform plane. `verifyMfaTempToken` rejects a dashboard token that lacks it and a platform
   * token that carries it, so the `?` expresses only that the two planes populate it differently —
   * it is never a value the caller may omit and have honoured. It is what lets the challenge
   * resolve the pending account tenant-scoped instead of by `sub` alone.
   */
  tenantId?: string

  /**
   * The subject's token **epoch** at issuance, in the plane named by `context`.
   *
   * The challenge token is a credential like any other — half of one, held by a caller who has
   * already proved the password — and it must die with the rest when the account's credentials
   * are rotated. Without this claim it did not: a password reset bumps the epoch and kills
   * every access token, but nothing touched an outstanding challenge record, so a token minted
   * before the reset stayed redeemable for its whole TTL and completing it issued a full
   * session under the *new* epoch.
   *
   * Optional for the same reason the access-token epochs are: a token issued before the field
   * existed carries none, which reads as `0` and is never rejected while the stored epoch is
   * also `0`, so the mechanism stays inert until the first bump.
   */
  epoch?: number

  /** Issued-at timestamp (Unix seconds). */
  iat: number

  /** Expiration timestamp (Unix seconds). */
  exp: number
}

/**
 * Discriminated union of every JWT payload type accepted by the auth system.
 */
export type AuthJwtPayload = DashboardJwtPayload | PlatformJwtPayload | MfaTempPayload
