/**
 * Shared JWT payload type definitions for @bymax-one/nest-auth.
 *
 * Redeclared here (instead of re-exported from `../../server`) so that the
 * shared subpath stays free of any server-side runtime imports. The shapes
 * are kept structurally compatible with the server-side definitions in
 * `src/server/interfaces/jwt-payload.interface.ts` — any change made there
 * must be reflected here.
 *
 * @remarks
 * These interfaces describe the shape of a **decoded and verified** token.
 * `iat` and `exp` are populated automatically by the JWT signing layer on
 * the server; they are not part of the signing payload.
 */

/**
 * JWT payload for dashboard (tenant) user access tokens.
 *
 * The literal `type: 'dashboard'` discriminant prevents accidental
 * acceptance of platform tokens in dashboard-scoped checks and vice-versa.
 */
export interface DashboardJwtPayload {
  /** Unique JWT ID (UUID v4) generated by the server for revocation tracking. */
  jti: string

  /** Subject — the authenticated user's internal identifier. */
  sub: string

  /** Tenant the user belongs to; used for data isolation. */
  tenantId: string

  /** User's assigned role within the tenant (e.g. `'admin'`, `'member'`). */
  role: string

  /** Discriminant literal — always `'dashboard'`. Prevents token type confusion. */
  type: 'dashboard'

  /** Snapshot of the user's account status at token issuance time. */
  status: string

  /** Whether MFA (TOTP) is currently enabled on the user's account. */
  mfaEnabled: boolean

  /** Whether the user completed MFA verification before this token was issued. */
  mfaVerified: boolean

  /** Issued-at timestamp (Unix seconds). */
  iat: number

  /** Expiration timestamp (Unix seconds). */
  exp: number
}

/**
 * JWT payload for platform administrator access tokens.
 *
 * Platform admins operate outside tenant boundaries, so this payload omits
 * `tenantId` and `status`. The literal `type: 'platform'` discriminant
 * ensures platform tokens are never accepted by dashboard-scoped checks.
 */
export interface PlatformJwtPayload {
  /** Unique JWT ID (UUID v4) generated by the server for revocation tracking. */
  jti: string

  /** Subject — the platform administrator's internal identifier. */
  sub: string

  /** Administrator's platform-level role (e.g. `'super_admin'`, `'support'`). */
  role: string

  /** Discriminant literal — always `'platform'`. Prevents token type confusion. */
  type: 'platform'

  /** Whether MFA (TOTP) is currently enabled on the admin's account. */
  mfaEnabled: boolean

  /** Whether the admin completed MFA verification before this token was issued. */
  mfaVerified: boolean

  /** Issued-at timestamp (Unix seconds). */
  iat: number

  /** Expiration timestamp (Unix seconds). */
  exp: number
}

/**
 * Short-lived JWT payload issued during an MFA challenge step.
 *
 * Grants no resource access on its own — exchanged for a full
 * {@link DashboardJwtPayload} or {@link PlatformJwtPayload} token after the
 * user supplies a valid OTP. Default lifetime is 5 minutes.
 */
export interface MfaTempPayload {
  /** Unique JWT ID (UUID v4) for single-use enforcement and revocation. */
  jti: string

  /** Subject — the user or admin identifier pending MFA completion. */
  sub: string

  /** Discriminant literal — always `'mfa_challenge'`. */
  type: 'mfa_challenge'

  /** Indicates which authentication context triggered the MFA challenge. */
  context: 'dashboard' | 'platform'

  /** Issued-at timestamp (Unix seconds). */
  iat: number

  /** Expiration timestamp (Unix seconds). */
  exp: number
}

/**
 * Discriminated union of every JWT payload type accepted by the auth system.
 */
export type AuthJwtPayload = DashboardJwtPayload | PlatformJwtPayload | MfaTempPayload
